rvm:
- 1.9.3
- 2.0.0
services:
- couchdb
env:
  global:
  - secure: CekvzarBrARhWE2/K1cof7SCnXBSzN/MijwO4hI+n1fITgk18gBEzlfyzd4BD68JZ2fVhPuWIqs+9WxBm+XLZUGYcgiBRovqN9JooElXgyV/CvqIEbJ7Xa4Vw/8mE2qJ1Ce54A8Sdkt4cfOZppyedUg/krzYw5uar3sDWWTt6z0=
  - secure: aSi+sIpBoS6VofHVUToRpvXrHG3avvdwG0frOBh+A8ijsjn3fOACeJm+ipQystYtCciZ09l5A/Q/Tkd1sogWy8ymU7bULVJsJb+aNJRM+00QYFelCLpxD8c6gP7aty/IRk7RfWqrii1ZHQ6KSeSqlJf6P6gYZOOA+1IQBO532vY=
notifications:
  email:
    - adrian.warman@uk.ibm.com
    - lbboe@us.ibm.com
  on_success: always
branches:
  except:
  - bluemix
before_install:
- sudo apt-get update
- sudo apt-get install python python-pip jq perl aspell aspell-en curl
script:
- ./scripts/spelling/spellcheck
- bundle exec middleman build --verbose
