#!/bin/bash

scriptDir="$(dirname $0)"

source "$scriptDir/spellcheck-lib"

function check {
  while read file; do
    echo 
    echo "checking $file"
    echo
    for word in `checkFile "$file"`; do
      #echo
      echo "$word"
      #cat "$file" | grep -n "$word" |
      #{
      #while read occurance; do
        #echo "$occurance"
        #line=`echo $occurance | cut -f1 -d ':'`
        #echo q | git blame -pL "$line,$line" "$file" | grep 'author '
      #done
      #}
    done
  done
}

report="$(changedFiles source | check | sed 's/$/<br>/' )"
if [[ "$(echo -n "$report" | grep -v '^<br>$' | grep -v '^checking ')" = '' ]]; then
  echo spell check passed!
else
  echo "$report"
  author=`git log | head -n 2 | tail -n 1 | sed 's/Author: //g'`
  curl -X POST https://api.sendgrid.com/api/mail.send.json \
     -d "to=$author" \
     -d "from=3b86d6cd-f285-40e8-b555-4137fa4057f6@appdirect.com" \
     -d "subject=Spell check" \
     -d "html=$report" \
     -H "Authorization: Bearer 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"
fi
