#!/bin/bash

function extract_code {
  IFS=''
  in_code=false
  while read -r line; do
    if [ "${in_code}" = true ] ; then
      if [ "$line" = '</pre>' ] ; then
        in_code=false
      else
        echo "$line";
      fi
    fi
    if [ "$line" = '<pre class="thebe">' ] ; then
      in_code=true
    fi
  done
}

extract_code <"$1" | bash -O expand_aliases >log 2>err &
PID="$!"
tail -f log &
PID2="$!"
tail -f err &
PID3="$!"
wait "$PID"
kill $PID2 $PID3
grep -v 'timed out' err >err2
if [ -s err2 ]; then
  rm err2 err log
  exit 1
else
  rm err2 err log
  exit 0
fi
